name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Backend install
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      # Backend tests
      - name: Run Backend Tests
        run: |
          cd backend
          npm test

      # Frontend install
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      # Frontend tests
      - name: Run Frontend Tests
        run: |
          cd frontend
          CI=true npm test -- --watchAll=false